fix required checks passing when job skipped
Signed-off-by: Anton-4 <17049058+Anton-4@users.noreply.github.com>

diff --git a/.github/workflows/ci_manager.yml b/.github/workflows/ci_manager.yml
--- a/.github/workflows/ci_manager.yml
+++ b/.github/workflows/ci_manager.yml
@@ -52,7 +52,7 @@ jobs:
     start-macos-x86-64-tests:
         needs: check-changes
         if: needs.check-changes.outputs.run_tests == 'full'
-        uses: ./.github/workflows/ubuntu_x86_64.yml
+        uses: ./.github/workflows/macos_x86_64.yml
 
     start-ubuntu-x86-64-tests:
         needs: check-changes
@@ -103,12 +103,16 @@ jobs:
       needs: [ran-full, ran-none]
       if: |
         always()
-        && contains(needs.*.result, 'success')
-        && !contains(needs.*.result, 'failure')
-        && !contains(needs.*.result, 'cancelled')
-        && !(needs.ran-full.result == 'skipped' && needs.ran-none.result == 'skipped')
       steps:
-          - run: echo "Workflow succeeded :)"
+        - name: Check previous job results
+          run: |
+            if [ "${{ needs.ran-full.result }}" != 'success' ] || [ "${{ needs.ran-none.result }}" != 'success' ]; then
+              echo "One or more jobs failed."
+              exit 1
+            fi
+
+        - run: echo "Workflow succeeded :)"
+
 
         
   
