check new zig files for top level comment (#7681)
* check new zig files for //!

* test

* test comment

* fix pub comment

* improvements

* remove test file

diff --git a/.github/workflows/ci_zig.yml b/.github/workflows/ci_zig.yml
--- a/.github/workflows/ci_zig.yml
+++ b/.github/workflows/ci_zig.yml
@@ -13,11 +13,38 @@ jobs:
               with:
                 version: 0.14.0
 
-            - run: |
+            - name: zig lints
+              run: |
                 ./ci/zig_lints.sh
-              
+
                 zig build check-fmt
-                
+
+            - name: zig top level comment check
+              run: |
+                NEW_ZIG_FILES=$(git diff --name-only --diff-filter=A origin/main HEAD | grep 'src/' | grep '\.zig$' || echo "")
+
+                if [ -z "$NEW_ZIG_FILES" ]; then
+                  # No new Zig files found
+                  exit 0
+                fi
+
+                FAILED_FILES=""
+
+                for FILE in $NEW_ZIG_FILES; do
+                  if ! grep -q "//!" "$FILE"; then
+                    echo "Error: $FILE is missing top level comment (//!)"
+                    FAILED_FILES="$FAILED_FILES $FILE"
+                  fi
+                done
+
+                if [ -n "$FAILED_FILES" ]; then
+                  echo "The following files are missing a top level comment: $FAILED_FILES"
+                  echo "Add a `//!` comment BEFORE any other code that explains the purpose of the file."
+                  exit 1
+                fi
+
+            - name: zig check
+              run: |
                 # -Dllvm incurs a costly download step, leave that for later.
                 # Just the do super fast check step for now.
                 zig build check -Dfuzz
