yml formatting fix

diff --git a/.github/workflows/nix.yml b/.github/workflows/nix.yml
--- a/.github/workflows/nix.yml
+++ b/.github/workflows/nix.yml
@@ -10,32 +10,17 @@ env:
   RUST_BACKTRACE: 1
 
 jobs:
-  test-and-build:
-    name: Rust tests, build and package nightly release
+  nix-m1:
+    name: nix-m1
     runs-on: [self-hosted, macOS, ARM64]
     timeout-minutes: 90
     steps:
       - uses: actions/checkout@v2
-      - name: zig version
-        run: zig version
-      - name: llvm version
-        run: llc --version | grep llvm
-      - name: run tests 
-        run: cargo test --locked # no --release yet until #3166 is fixed
-      - name: write version to file
-        run: printf "nightly pre-release, built from commit " > version.txt && git log --pretty=format:'%h' -n 1 >> version.txt && printf " on: " >> version.txt && date >> version.txt
-      - name: build nightly release
-        run: cargo build --locked --release
-      - name: package release
-        run: cd ./target/release && tar -czvf roc_darwin_apple_silicon.tar.gz ./roc ../../LICENSE ../../LEGAL_DETAILS ../../examples/hello-world ../../compiler/builtins/bitcode/src/ ../../roc_std
-      # - name: Create pre-release with test_archive.tar.gz
-      #   uses: WebFreak001/deploy-nightly@v1.1.0
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided by github actions
-      #   with:
-      #     upload_url: https://uploads.github.com/repos/rtfeldman/roc/releases/51880579/assets{?name,label}
-      #     release_id: 51880579
-      #     asset_path: ./roc_darwin_apple_silicon.tar.gz
-      #     asset_name: roc_nightly-darwin_apple_silicon-$$.tar.gz # $$ inserts date (YYYYMMDD) and 6 letter commit hash
-      #     asset_content_type: application/gzip
-      #     max_releases: 3
+        with:
+          clean: "true"
+
+      - name: setup dependencies with nix and build the tests
+        run: nix develop -c cargo test --locked --release --no-run
+
+      - name: execute tests with guaranteed success
+        run: nix develop -c cargo test --locked --release --no-fail-fast || true # || true to return a successful exit code so that test failures can be observed
