run m1 tests but succeed on fail

diff --git a/.github/workflows/nix.yml b/.github/workflows/nix.yml
--- a/.github/workflows/nix.yml
+++ b/.github/workflows/nix.yml
@@ -22,4 +22,4 @@ jobs:
           clean: "true"
 
       - name: setup dependencies with nix, build and test
-        run: nix develop -c cargo test --locked --release --no-run
+        run: nix develop -c cargo test --locked --release --no-fail-fast || true # || true to return a successful exit code so that test failures can be observed
